spring:
  datasource:
    url: jdbc:mysql://localhost:3306/animes?createDatabaseIfNotExist=true
    username: root
    password: guest
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

server:
  port: 1980
  error:
    include-stacktrace: on_param

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus