global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'learning-kotlin'
    static_configs:
      - targets:
          - host.docker.internal:8080